version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_DB_ADMIN_USER=admin
      - INFLUXDB_DB_ADMIN_PASSWORD=Password1
    restart: on-failure:10
    ports:
      - '8086:8086'
    networks:
      - comp

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9092:9092'
    expose:
      - "9093"
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.0.46 #your IP
      - KAFKA_CREATE_TOPICS="elte"
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    links:
      - zookeeper:zookeeper
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
  
  spark:
    image: "jupyter/pyspark-notebook"
    ports:
      - '8888:8888'
      - '4040:4040'
      - '4041:4041'
    links:
      - "kafka:kafka-server" # allows spark notebook to discover kafka service by name "kafka-server"
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/work
      

    depends_on:
      - zookeeper 

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  comp:
    driver: bridge