version: "3"

services:
  # pyspark:
  #   image: "jupyter/all-spark-notebook"
  #   ports:
  #     - '8888:8888'
  #     - '4040:4040'
  #     - '4041:4041'
  #   volumes:
  #     - type: bind
  #       source: ./
  #       target: /home/jovyan/work
  #   networks:
  #     - comp

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_DB_ADMIN_USER=admin
      - INFLUXDB_DB_ADMIN_PASSWORD=Password1
    restart: on-failure:10
    ports:
      - '8086:8086'
    networks:
      - comp

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: wurstmeister/kafka:2.11-1.1.1 #The spark consumer doesn't work with scala 2.12
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: 192.168.56.1 #your IP
  #     KAFKA_CREATE_TOPICS: "wiki-changes:1:1"
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9092:9092'

    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper 

  # zookeeper:
  #   image: 'bitnami/zookeeper:latest'
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: 1
    
  # kafka:
  #   image: 'bitnami/kafka:2.8.1'
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_HOSTNAME: localhost
  #     ALLOW_PLAINTEXT_LISTENER: 1

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

  spark:
    image: jupyter/all-spark-notebook:spark-3.1.1
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - "kafka:kafka-server" #allows spark notebook to discover kafka service by name "kafka-server"
    volumes:
      - ../notebooks:/home/jovyan/work/notebooks/

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  comp:
    driver: bridge