version: "3"

services:
  spark:
    image: "jupyter/pyspark-notebook"
    ports:
      - '8888:8888'
      - '4040:4040'
      - '4041:4041'
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/work
    networks:
      - comp

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_DB_ADMIN_USER=admin
      - INFLUXDB_DB_ADMIN_PASSWORD=Password1
    restart: on-failure:10
    ports:
      - '8086:8086'
    networks:
      - comp

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  comp:
    driver: bridge